version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run: 
         - name: Install Dependencies
         - command: pip install --user -r requirements.txt
      - run:
         - name: Run Tests 
         - command: bash runTests.sh
